### PR TITLE
Add godef

### PR DESCRIPTION
**Pull request by taterbase**
This cribs a lot from the godocget, I'd like to get it cleaned up before merging but this works right now.

### CODE REVIEW

**Comment by syscrusher** [comment]
Great work, I appreciate you contributing to this bundle.
I went ahead and merged this because it's functional and I'm not too concerned about the minor repetition. Sometimes tools change so it's not always worth factoring out minor stuff. This should also get our git histories in order and make merges more straightforward.

**Comment by taterbase** [comment]
Awesome! Appreciate the expedient merge.

**Comment by sorbits** [comment]
The _Go → Def_ action is bound to <kbd>⌘D</kbd> and lack a scope selector of `source.go`.

This means using <kbd>⌘D</kbd> to duplicate a file in the file browser now trigger this command.

/cc @Infininight

**Comment by syscrusher** [comment]
Changed. That's a nifty shortcut I didn't know about. Thanks!

**Comment by infininight** [comment]
@syscrusher That shortcut conflicts as well (Find Again), there aren't any free shortcuts using `⌘` actually. A shortcut that is in use for this sort of command is `⇧⌘D`.

**Comment by taterbase** [comment]
It's my opinion that godef is used quite a bit and should have a 2-key activation. Is there a Ctrl-{key} that could work?

**Comment by taterbase** [comment]
Also, would I be misunderstanding if it seems that just adding the scope selector should be enough to fix the duplicate file bug, allowing us to continue using ⌘D?

**Comment by infininight** [comment]
Surprisingly no, every single command plus a letter shortcut is already taken. Adding the scope greatly reduces the issue, because it will only be active when a Go document is frontmost. But overriding the key isn't really desirable in this case because it breaks a basic function in the app with a completely different one. Overriding a built-in function can be good in some cases when you provide a better more custom version of a built-in command but this isn't the case here.

**Comment by syscrusher** [comment]
@taterbase Any preference for the final shortcut?

**Comment by taterbase** [comment]
It sounds like  `⇧⌘D` is available? That would be a good alternative.

**Comment by msoap** [comment]
What about `Ctrl-]` like in Vim?

**Comment by sorbits** [comment]
<kbd>⇧⌘D</kbd> is available and already has a somewhat assigned meaning as “go to something” (in C and Ruby we use it to go to the file included/required, alternatively opening a dialog when not on such line).

The <kbd>⌃]</kbd> will be very hard to reach on most European keyboard layouts.

@infininight Might be worth making some standard proxy items in the Source bundle so bundle items can use semantic classes and leave the key equivalent empty.

**Comment by syscrusher** [comment]
⇧⌘D is currently used by our "Open Package" command. It fits the common usage, but its package resolution abilities are limited and it has been on my radar to rewrite it.
Def fits most of the common usage, except opening a dialog if no identifier is selected. I will add that, remove Open Package, then use ⇧⌘D for this command.

**Pull request merged**
